# Generated by Django 3.1 on 2020-08-24 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[a-z, A-Z]*$', 'Only Alphabetic Characters (A-Z) Are Allowed.')]),
        ),
    ]
